### ISSUE TITLE
A shaded version of this plugin would be helpful

### ISSUE THREAD

**Issue by mslinn** [scijava/scripting-kotlin#1]
This plugin depends on JLine, which breaks projects that have other dependencies which also bundle JLine.

**Comment by ctrueden** [comment]
Very sorry for the lack of reply till now, @mslinn!

For reasons of consistency, I am reluctant to create a shaded artifact. I hate to be inflexible, but the core issue lies with the [unshaded uber-jars](https://imagej.net/Uber-JAR) produced by those other projects. Those libraries ought to provide non-uber-JAR-based artifacts with proper dependencies, so that Maven dependency resolution can happen properly.

What do you think the chances of that happening are? Which other projects bundle JLine into an uber-JAR? If there is no hope of addressing the issue on their side, and combining those projects with scripting-kotlin is especially useful, perhaps we could make an exception and produce a shaded uber-JAR.

One more question first, though: do you still need this component, now that Kotlin has its own official JSR-223 script engine? This component really only exists to implement the SciJava script API for SciJava-based scripting, particularly [within ImageJ](https://imagej.net/Scripting).

**Comment by mslinn** [comment]
It is now nearly 2 years after I posted this issue. No longer relevant.
